butia_emotions:

  eyebrown:

    standard:
      rightY: 50
      leftY: 50
      rightRotation: 50
      leftRotation: 120
      
    happy:
      rightY: 80
      leftY: 80
      rightRotation: 43
      leftRotation: 120

    sad:
      rightY: 10
      leftY: 10
      rightRotation: 170
      leftRotation: 10

    rage:
      rightY: 30
      leftY: 30
      rightRotation: 75
      leftRotation: 100

    scared:
      rightY: 90
      leftY: 90
      rightRotation: 35
      leftRotation: 130

    doubt:
      rightY: 90
      leftY: 60
      rightRotation: 80
      leftRotation: 120

    sleepy:
      rightY: 10
      leftY: 10
      rightRotation: 35
      leftRotation: 125
    
  eyelid:

    standard:
      h: 70
      frequency: 0
      right: 70
      left: 70

    happy:
      h: 75
      frequency: 0
      right: 60
      left: 60

    sad:
      h: 60
      frequency: 0
      right: 55
      left: 55

    rage:
      h: 75
      frequency: 0
      right: 50
      left: 50

    scared:
      h: 60
      frequency: 0
      right: 90
      left: 90
    
    doubt:
      h: 80
      frequency: 0
      right: 60
      left: 60
    
    sleepy:
      h: 100
      frequency: 0
      right: 30
      left: 30

  neck:

    standard:
      horizontal: 180
      vertical: 180

    happy:
      horizontal: 180
      vertical: 180
    
    sad:
      horizontal: 180
      vertical: 180

    rage:
      horizontal: 180
      vertical: 180

    scared:
      horizontal: 180
      vertical: 180
    
    doubt:
      horizontal: 180
      vertical: 180
    
    sleepy:
      horizontal: 180
      vertical: 180