butia_emotions:

  eyebrown:

    standard:
      rightY: 50
      leftY: 50
      rightRotation: 90
      leftRotation: 90
      
    happy:
      rightY: 60
      leftY: 60
      rightRotation: 80
      leftRotation: 80

    sad:
      rightY: 80
      leftY: 80
      rightRotation: 70
      leftRotation: 70 

    rage:
      rightY: 30
      leftY: 50
      rightRotation: 115
      leftRotation: 125

    scared:
      rightY: 0
      leftY: 10
      rightRotation: 80
      leftRotation: 100

    doubt:
      rightY: 10
      leftY: 80
      rightRotation: 115
      leftRotation: 90

    sleepy:
      rightY: 100
      leftY: 90
      rightRotation: 80
      leftRotation: 90
    
  eyelid:

    standard:
      h: 70
      frequency: 0
      right: 50
      left: 50

    happy:
      h: 75
      frequency: 0
      right: 50
      left: 50

    sad:
      h: 60
      frequency: 0
      right: 55
      left: 55

    rage:
      h: 75
      frequency: 0
      right: 80
      left: 70

    scared:
      h: 60
      frequency: 0
      right: 90
      left: 60
    
    doubt:
      h: 80
      frequency: 0
      right: 60
      left: 50
    
    sleepy:
      h: 100
      frequency: 0
      right: 120
      left: 110

  neck:

    standard:
      horizontal: 180
      vertical: 180

    happy:
      horizontal: 180
      vertical: 180
    
    sad:
      horizontal: 180
      vertical: 180

    rage:
      horizontal: 180
      vertical: 180

    scared:
      horizontal: 180
      vertical: 180
    
    doubt:
      horizontal: 180
      vertical: 180
    
    sleepy:
      horizontal: 180
      vertical: 180

  eyes:

    standard:
      horizontal: 65
      vertical: 43

    happy:
      horizontal: 65
      vertical: 57

    sad:
      horizontal: 65
      vertical: 10

    rage:
      horizontal: 65
      vertical: 57

    scared:
      horizontal: 65
      vertical: 57
    
    doubt:
      horizontal: 65
      vertical: 43
    
    sleepy:
      horizontal: 65
      vertical: 43

  jaw:
  
    standard:
      percent: 80

    happy:
      percent: 100

    sad:
      percent: 75

    rage:
      percent: 75

    scared:
      percent: 100
    
    doubt:
      percent: 75
    
    sleepy:
      percent: 75